### ISSUE TITLE
Non-exported utils

### ISSUE THREAD

**Issue by wkrasnicki** [konvajs/react-konva-utils#1]
I have noticed that the source code contains text-editor and editable-text components, which seem like a great improvement from the vanilla JS - React mix from the Konva tutorial. I would like to ask why aren't they exported?

**Comment by lavrton** [comment]
I didn't polish the implementation and API yet. As soon as it is ready I will make it public.

**Comment by vermillion23** [comment]
Is there a way to use this library so far? the library is mention in the official docs as the only way to change zindex in conva js with react https://konvajs.org/docs/react/Canvas_Portal.html

**Comment by lavrton** [comment]
You can use it just fine. `Portal` and `Html` are already there and works very stable.

**Comment by lavrton** [comment]
>  only way to change zindex in conva js with react

It is not the only way: https://konvajs.org/docs/react/zIndex.html
But I do recommend it when you need something like absolute position.
