### ISSUE TITLE
Should replace ReactDOM.render use with createRoot for React 18 compatability

### ISSUE THREAD

**Issue by kevinflo** [konvajs/react-konva-utils#13]
Currently using `react-konva-utils` `Html` in a React 18 project results in the following error

`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

I'm not super familiar with the lib but I think that stems from https://github.com/konvajs/react-konva-utils/blob/fe3e88b4264b1cac366876aca4d78a2490afa95a/src/html.tsx#L104

**Comment by lavrton** [comment]
Done. Should be resolved with `v0.3.0`.
