### ISSUE TITLE
[error] Module parse failed: Unexpected token (102:44) err

### ISSUE THREAD

**Issue by masudhossain** [konvajs/react-konva-utils#14]
Getting an error when trying to use this npm package. 
package.json below 
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-konva": "^17.0.2-6",
"react-konva-utils": "^0.3.0",
"konva": "^7.0.6",

<img width="628" alt="image" src="https://user-images.githubusercontent.com/16615124/175753997-6ba04daf-51e7-40fb-a042-e59feb6d3ef7.png">

**Comment by lavrton** [comment]
This should be fixed with the last `konva`, `react-konva` and `react-konva-utils` versions.
