### ISSUE TITLE
Bridge Context with Html Component

### ISSUE THREAD

**Issue by OmegaHawkeye** [konvajs/react-konva-utils#15]
Hi,

how would I achieve to bridge a context when using the Html Component.

I tried it as when bridging context with react-konva but that doesn't seem to work.

For clearance thats the code I tried.

```js
  <CommandContext.Consumer>
      {(value) => (
        <Html transform={false}>
          <CommandContext.Provider value={value}>
            <QuickBar />
          </CommandContext.Provider>
        </Html>
      )}
  </CommandContext.Consumer>
``` 

It gets mentioned on the [Render DOM elements inside a canvas stage](https://konvajs.org/docs/react/DOM_Portal.html) example but there is no documentation of how u would do it.

Thx in advance for ur answer

**Comment by lavrton** [comment]
Can you make a full and small demo? You may need to make two bridges. From react-dom to react-konva, and from react-konva back to react-dom.

**Comment by OmegaHawkeye** [comment]
Thx for the response.
I dont need it anymore since I placed it in a parent Component next to the whole react-konva thing 
and then added the appropiate styles to make it appear on top of the canvas. 

But still thx for the quick response and thx for these wonderful libraries
