### ISSUE TITLE
Warning: Attempted to synchronously unmount a root while React was already rendering

### ISSUE THREAD

**Issue by psychedelicious** [konvajs/react-konva-utils#19]
I am getting this error when my `Html`  component unmounts:

```javascript
react_devtools_backend.js:4045 Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.
    at Html (http://localhost:5173/node_modules/.vite/deps/react-konva-utils.js?v=4835bfa9:40:15)
```

**Comment by Victorasa21** [comment]
Hello, 

I was getting the same error pointed out above 

![image](https://user-images.githubusercontent.com/33321398/202160955-14c234f3-ee4c-4f6e-853c-4419e5d6a638.png)

But after using the solution (switching to useLayoutEffect), changing my local node_modules, I still having the warning but in a different way. 

![image](https://user-images.githubusercontent.com/33321398/202161289-3a668dbd-b879-4dd7-912a-9c69be177d41.png)

The solution for me in this case, was to completely remove this from html.js: 

![image](https://user-images.githubusercontent.com/33321398/202161727-9800f8dd-4c68-4c57-be73-f78d60bd32a8.png)

**Comment by lavrton** [comment]
It may lead to memory leaks, if you remove that.

**Comment by Reyems** [comment]
For me this cleared up the problem..

React.useEffect(() => {
        return () => {
            setTimeout(() => {
                root.unmount();
              });
        };
    }, []);
