### ISSUE TITLE
Reference for group in Html component

### ISSUE THREAD

**Issue by ierehon1905** [konvajs/react-konva-utils#21]
Hi, thank you for your awesome library. I was wondering if it is possible to pass the ref to the <Html/> component.

My use case is manually passing through some of the events from html to konva. Right now I stick to `konva._eventhandlername`. 

https://github.com/konvajs/react-konva-utils/blob/190fbf4d11ec709d711a889b8f0483f5cbdb6346/src/html.tsx#L36

**Comment by lavrton** [comment]
Can you explain why do you need it?

**Comment by ierehon1905** [comment]
> Can you explain why do you need it?

For example one of the use cases included dragging html elements containing text rendered through this library. I was wondering if I could directly pass the mouse/pointer down event from html to konva group. Because right now if im not mistaken when I pass the event to bare konva with `konva._eventhandlername` it recalculated the position or stuff. I just thought it would be easier to pass the events manually and directly to the node I intend.

**Comment by lavrton** [comment]
Sorry, I still don't understand it. Please create a demo.
