### ISSUE TITLE
Markup rendered using Html is not showing in toDataURL

### ISSUE THREAD

**Issue by MContagious** [konvajs/react-konva-utils#32]
Sample code base

https://codesandbox.io/s/spring-wind-4j3ycg?file=/src/index.js:466-508

after rendering html markup using Html (imported from react-konva-utils) is not showing in toDataURL output.

Expected: As the html is part of Stage the stage should show the html also in the image generated from stage.

**Comment by lavrton** [comment]
That a lot for posting a workaround.

For now, I am thinking about this issue as "wont fix". I can't find any suitable solutions that can be part of the library to fix it automatically. So we have to do some manual steps into insert HTML directly into canvas.
