### ISSUE TITLE
[Quick note]: There is a minor error in the Konva documentation

### ISSUE THREAD

**Issue by devysi0827** [konvajs/react-konva-utils#34]
https://konvajs.org/docs/react/DOM_Portal.html

There is an issue with the `<Html />` tag on this page.
When numbers are added to the properties inside `divProps > style`, it does not work as expected
However, it works when these properties are added as strings along with their units.

``` javascript
// example
<Html
    divProps={{
      style: {
        position: 'absolute',
        top: 10, // it doesn't work
        left: '10px', // it works well
      },
    }}
  >
    <input placeholder="DOM input from Konva nodes" />
  </Html>
```

I had some difficulty finding this, so it might be helpful for others if the documentation is updated.

In my opinion, using number(60) is more intuitive, user-friendly, and consistent with other Konva variables than the string '60px'. If you find the time later, converting it to a number would be even better.

I have received a lot of help from your fantastic library. I am very grateful, and I conclude this message. Thank you.

**Comment by lavrton** [comment]
That is intentional. `divProps` are just props of regular `div` element. So styles are passed there too and it is CSS styles. `<Html />` component is not doing any modifications for the styles.
