### ISSUE TITLE
unable to use clip functionality for HTML component

### ISSUE THREAD

**Issue by Rushi-Kumar** [konvajs/react-konva-utils#35]
If the HTML component is placed outside the clip, it will remain visible when using the clip function.

![Screenshot 2024-01-31 at 8 31 06 AM](https://github.com/konvajs/react-konva-utils/assets/25897999/18694271-457d-45df-9d35-b358799b0dd4)

Clip is function is used to make only 3 lines visible, all other react konva components are hidden expect for HTML components, 

Please help me how to handle this situation.
Thank you in advance

**Comment by lavrton** [comment]
HTML is not part of the canvas rendering, so clip doesn't affect it. I recommend not to use <Html /> for and icon. It is better to use <Html /> for "temporary" components, such as tooltips or some inputs.
