### ISSUE TITLE
Html component does not react to zIndex divProps change

### ISSUE THREAD

**Issue by GuySpotnix** [konvajs/react-konva-utils#5]
Hi,

I'm trying to override (dynamically) the wrapping div zIndex property by setting the divProps in the following way:
```
<Html divProps={{style: {zIndex}}} groupProps={{}}>
....
</Html>
```

The zIndex is set to 10 always, and not being override with style as expected.

I have noticed that handleTransform method of Html component is setting the zIndex to 10 on every transform.
A hotfix might be
```
div.style.zIndex = style.zIndex || '10';
```

**Comment by lavrton** [comment]
Please try it again with `react-konva-utils@0.1.5`.
