### ISSUE TITLE
Html - Possible to translate but not rotate?

### ISSUE THREAD

**Issue by dylinmaust** [konvajs/react-konva-utils#7]
Is it possible to translate the div rendered by the Html component but not scale? or set scale to 1.0?

**Comment by lavrton** [comment]
What is your use case?

**Comment by dylinmaust** [comment]
@lavrton I am hoping to show a Material UI dialog based on the mouse position using the `<Html>` component. But I'd like the dialog to have a constant scale rather than scale with the stage. I don't know if that makes sense though

**Comment by lavrton** [comment]
That make a lot of sense to me. Can you try this with the last version (just published)?

```js
<Html transformFunc={(attrs) => ({ ...attrs, scaleX: 1, scaleY: 1 })}>
```

**Comment by dylinmaust** [comment]
@lavrton Thank you for the incredibly fast turnaround! Confirmed that it's working perfectly on react-konva-utils@^0.2.0
