### ISSUE TITLE
React peer dependencies on react-konva and react-konva-utils

### ISSUE THREAD

**Issue by andres-palumbo** [konvajs/react-konva-utils#8]
First of all, thank you for such an amazing library!

I'm seeing that this library has a different React peer dependency version than react-konva:

react-konva-utils:

```
"react": "^17.0.2",
"react-dom": "^17.0.2"
```
react-konva:

```
"react": ">=16.8.0",
"react-dom": ">=16.8.0"
```

**Comment by lavrton** [comment]
Is it an issue for you?
