### ISSUE TITLE
Html component does not render with new transformFunc values

### ISSUE THREAD

**Issue by ErikBavenstrand** [konvajs/react-konva-utils#9]
The component only re-renders once transform changes value due to useLayoutEffect only triggering on change on transform or divProps. Should the Html component not re-render with the new values in the transformFunc each render?

**Comment by lavrton** [comment]
So, you want to recalculate transform when `transformFunc` is changed, right?

**Comment by ErikBavenstrand** [comment]
Yes, for example when the `transformFunc` is dependent on the state of a component I want <Html> to update according to the new values before render. Currently, I'm sending bogus values through `divProps` to force an update.

**Comment by lavrton** [comment]
Make sense. Do you want to make a Pull Request?

**Comment by ErikBavenstrand** [comment]
Sure, I’ll get on it soon
